/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package syspaetelas;

import controleConexao.Conexao;
import java.sql.*;

/**
 *
 * @author carlo
 */
public class CadastroAtendimento extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAtendimento
     */
    public CadastroAtendimento() {
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        buscaAlunos();
        buscaProfissional();
        cmbbxEspecialidade.removeAllItems();
    }

    private void buscaAlunos(){
        String busca = "Select nome from aluno";
        Conexao con = new Conexao();
        ResultSet rs = con.executaBusca(busca);
        try {
            while(rs.next()){
                cmbbxAluno.addItem(rs.getString("nome"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void buscaProfissional(){
        String busca = "Select nome from profissional";
        Conexao con = new Conexao();
        ResultSet rs = con.executaBusca(busca);
        try {
            while(rs.next()){
                cmbbProfissional.addItem(rs.getString("nome"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
 
   }
    
    private int buscaEspecialidadeID(){
        String buscaId = "select fk_especialidade_idespecialidade from profissional where nome like '"+cmbbProfissional.getSelectedItem().toString()+"'";
        int id = 0;
        Conexao con = new Conexao();
        ResultSet rs = con.executaBusca(buscaId);
        try {
            while(rs.next()){
                id = rs.getInt("fk_especialidade_idespecialidade");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return id;
    }
    
    private void buscaEspecialidadeNome(){
        cmbbxEspecialidade.removeAllItems();
        int id = buscaEspecialidadeID();
        String buscaNome = "Select nome from especialidade where CAST(idespecialidade AS TEXT) like '"+id+"'";
        Conexao con = new Conexao();
        ResultSet rs = con.executaBusca(buscaNome);
        try {
            while(rs.next()){
                cmbbxEspecialidade.addItem(rs.getString("nome"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private int idAluno(){        
        String busca = "Select * from aluno where nome like '"+cmbbxAluno.getSelectedItem().toString()+"%'";
        Conexao con = new Conexao();
        ResultSet rs = con.executaBusca(busca);
        int id = 0;
        try {
            while(rs.next()){
                id = rs.getInt("idaluno");
            }
        } catch (Exception e) {
        }
        return id;
    }
    
    private int idProfissional(){
        String busca = "Select * from profissional where nome like '"+cmbbProfissional.getSelectedItem().toString()+"%'";
        Conexao con = new Conexao();
        ResultSet rs = con.executaBusca(busca);
        int id = 0;
        try {
            while(rs.next()){
                id = rs.getInt("idprofissional");
            }
        } catch (Exception e) {
        }
        return id;
    }
    
    private String preparaSQL(){        
        return "Insert into atendimento (data_do_atendimento, motivo_do_atendimento, diagnostico, tratamento, fk_aluno_idaluno, fk_profissional_idprofissional, aluno, profissional, especialidade) "
                    + "values ('"+txtfldDataAtendimento.getText()+"', '"+txtMotivoAtendimento.getText()+"', '"+txtDiagnostico.getText()+"'"
                    + ", '"+txtTratamento.getText()+"', '"+idAluno()+"', '"+idProfissional()+"', '"+cmbbxAluno.getSelectedItem().toString()+"', '"+cmbbProfissional.getSelectedItem().toString()+"', '"+cmbbxEspecialidade.getSelectedItem().toString()+"')";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        cmbbxAluno = new javax.swing.JComboBox<>();
        cmbbProfissional = new javax.swing.JComboBox<>();
        cmbbxEspecialidade = new javax.swing.JComboBox<>();
        txtfldDataAtendimento = new javax.swing.JFormattedTextField();
        lblDataAtendimento = new javax.swing.JLabel();
        lblEspecialidade = new javax.swing.JLabel();
        lblAluno = new javax.swing.JLabel();
        lblProfissional = new javax.swing.JLabel();
        btnAnamnese = new javax.swing.JButton();
        lblMotivoAtendimento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivoAtendimento = new javax.swing.JTextArea();
        lblDiagnostico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        lblTratamento = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTratamento = new javax.swing.JTextArea();

        setTitle("Cadastrar Atendimento");
        setResizable(false);

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cmbbxAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmbbProfissional.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbbProfissional.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbProfissionalItemStateChanged(evt);
            }
        });
        cmbbProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbProfissionalActionPerformed(evt);
            }
        });
        cmbbProfissional.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbbProfissionalPropertyChange(evt);
            }
        });

        cmbbxEspecialidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            txtfldDataAtendimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfldDataAtendimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblDataAtendimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDataAtendimento.setText("Data do atendimento");

        lblEspecialidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEspecialidade.setText("Especialidade");

        lblAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAluno.setText("Aluno");

        lblProfissional.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProfissional.setText("Profissional");

        btnAnamnese.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAnamnese.setText("Anamnese");
        btnAnamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnamneseActionPerformed(evt);
            }
        });

        lblMotivoAtendimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMotivoAtendimento.setText("Motivo do atendimento");

        txtMotivoAtendimento.setColumns(20);
        txtMotivoAtendimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMotivoAtendimento.setRows(5);
        jScrollPane1.setViewportView(txtMotivoAtendimento);

        lblDiagnostico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiagnostico.setText("Diagnóstico");

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiagnostico.setRows(5);
        jScrollPane2.setViewportView(txtDiagnostico);

        lblTratamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTratamento.setText("Tratamento");

        txtTratamento.setColumns(20);
        txtTratamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTratamento.setRows(5);
        jScrollPane3.setViewportView(txtTratamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTratamento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAluno)
                                            .addComponent(lblProfissional))
                                        .addGap(0, 217, Short.MAX_VALUE))
                                    .addComponent(cmbbxAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbbProfissional, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEspecialidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDataAtendimento)
                                        .addGap(135, 135, 135))
                                    .addComponent(cmbbxEspecialidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSalvar)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtfldDataAtendimento)
                                                .addGap(38, 38, 38)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAnamnese)
                                            .addComponent(btnSair)))))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDiagnostico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMotivoAtendimento, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataAtendimento)
                    .addComponent(lblAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldDataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnamnese))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidade)
                    .addComponent(lblProfissional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbxEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMotivoAtendimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDiagnostico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTratamento)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnSalvar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnamneseActionPerformed
        // TODO add your handling code here:
        CadastroAnamnese tela06 = new CadastroAnamnese();
    }//GEN-LAST:event_btnAnamneseActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Conexao con = new Conexao();
        int insert = con.executaInsert(preparaSQL());
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        TelaConfirma sair = new TelaConfirma(this, true);
        if(sair.getReturnStatus()==1) this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void cmbbProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbProfissionalActionPerformed
        // TODO add your handling code here:
        buscaEspecialidadeNome();
    }//GEN-LAST:event_cmbbProfissionalActionPerformed

    private void cmbbProfissionalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbbProfissionalPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbProfissionalPropertyChange

    private void cmbbProfissionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbProfissionalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbProfissionalItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnamnese;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbbProfissional;
    private javax.swing.JComboBox<String> cmbbxAluno;
    private javax.swing.JComboBox<String> cmbbxEspecialidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblDataAtendimento;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblMotivoAtendimento;
    private javax.swing.JLabel lblProfissional;
    private javax.swing.JLabel lblTratamento;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextArea txtMotivoAtendimento;
    private javax.swing.JTextArea txtTratamento;
    private javax.swing.JFormattedTextField txtfldDataAtendimento;
    // End of variables declaration//GEN-END:variables
}
